version: '3.8'
services:
    postgree:
        image: postgres:latest
        container_name: postgree
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        ports:
            - '5432:5432'

    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - '6379:6379'
